driver=com.mysql.jdbc.Driver
url=jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
username=root
password=root

redis.url=127.0.0.1
redis.port=6379
redis.password=

mongo.host=127.0.0.1
mongo.port=27017
mongo.username=
mongo.password=
mongo.dbname=local
mongo.writeNumber=1
mongo.connectionsPerHost=20
mongo.threadsAllowedToBlockForConnectionMultiplier=10
mongo.autoConnectRetry=true
mongo.connectTimeout=10000
mongo.maxWaitTime=12000
mongo.writeTimeout=5000
mongo.socketKeepAlive=true
mongo.socketTimeout=1500
mongo.slaveOk=true
mongo.writeFsync=true